src/HDV/AdminBundle/Entity/Images.php
<?php
namespace HDV\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity
 * @ORM\Table(name="hdv_images")
 * @ORM\HasLifecycleCallbacks
 * @ORM\Entity()
 */
class Images
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    public $name;

    /**
     * @Assert\File(
     *     maxSize = "64M",
     * )
     */
    private $file;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    public $path;

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
         $this->file = $file;
        // check if we have an old image path
        if (isset($this->path)) {
            // store the old name to delete after the update
            $this->temp = $this->path;
            $this->path = null;
        } else {
            $this->path = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir().'/'.$this->path;
    }

    protected function getUploadRootDir($idvente)
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.$this->getUploadDir($idvente);
    }

    protected function getUploadDir($idvente)
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'bundles/images/ventes/'.$idvente;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        // la propriété « file » peut être vide si le champ n'est pas requis
        if (null === $this->file) {
            return;
        }

        if ($this->path != $this->file->getClientOriginalName()) {
            $this->path = $this->file->getClientOriginalName();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload($idvente)
    {
        // la propriété « file » peut être vide si le champ n'est pas requis
        if (null === $this->file) {
            return;
        }

        $file_name = $this->file->getClientOriginalName();

        // la méthode « move » prend comme arguments le répertoire cible et
        // le nom de fichier cible où le fichier doit être déplacé
        if (!file_exists($this->getUploadRootDir($idvente))) {
            mkdir($this->getUploadRootDir($idvente), 0775, true);
        }
        $this->file->move(
            $this->getUploadRootDir($idvente), $file_name
        );
        $this->file = null;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Document
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set path
     *
     * @param string $path
     *
     * @return Document
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }
}

src/HDV/AdminBundle/Resources/views/Ventes/add.html.twig
{% extends "HDVAdminBundle:Default:index.html.twig" %}
{% block scripts %}
<script type="text/javascript">
    $(function () {

        // A change sélection de fichier
        $('#formup').find('input[type=file]').on('change', function (e) {
            var files = $(this)[0].files;

            if (files.length > 0) {
                // On part du principe qu'il n'y qu'un seul fichier
                // étant donné que l'on a pas renseigné l'attribut "multiple"
                var file = files[0],
                    $image_preview = $('#image_preview');

                // Ici on injecte les informations recoltées sur le fichier pour l'utilisateur
                $image_preview.find('.thumbnail').removeClass('hidden');
                $image_preview.find('.btn').removeClass('hidden');
                $image_preview.find('img').attr('src', window.URL.createObjectURL(file));
            }
        });

        // Bouton "Annuler"
        $('#image_preview').find('button[type="button"]').on('click', function (e) {
            e.preventDefault();

            $('#formup').find('input[name="hdv_ventesbundle_ventes[image][file]"]').val('');
            $('#image_preview').find('.thumbnail').addClass('hidden');
            $('#image_preview').find('.btn').addClass('hidden');
        });
    });

    $(".datetimepicker").datetimepicker({
    locale: 'fr',
    useCurrent: false,
    sideBySide: true
});

$(document).ready(function(){
  $('input').iCheck({
    checkboxClass: 'icheckbox_flat-blue',
    radioClass: 'iradio_flat-blue'
  });
});
</script>
{% endblock %}
{% block body %}

<h2>Ajouter une vente</h2>
<div class="grad"></div>
<a href="{{ path('hdv_admin_ventes_home',{ 'period' : 'futur' }) }}" class="btn btn-default"><span class="fa fa-lg  fa-arrow-left" style="margin-right:5px;"></span> Retour</a>
<br/><br/>
<div class="box box-primary">
           <div class="box-header with-border">
             <h3 class="box-title">Principal</h3>
           </div>
            <div class="box-body">
{{ form_start(form, {'attr': {'id': 'formup'}}) }}


<br/>
  <div class="row">
      <div class="col-md-6">
        <div class="row">
            <div class="col-md-8">
        <label for="couv" class="col-sm-2 control-label" style="width: 250px">Couverture :</label>
        <a class="btn btn-info btn-lg" style="width: 100px;margin-left:18px;">
      <label for="{{ form.image.file.vars.id }}" style="width:100px;height:35px;float:left;"><i class="glyphicon glyphicon-save-file fa-3x"></i></label></a>
      {{ form_errors(form.image.file) }}
        {{ form_widget(form.image.file, {'attr': {'class': 'inputfile'}}) }}
      </div>
      <div class="col-md-4">
        <div id="image_preview" style="height:185px;">
        <div class="thumbnail hidden">
            <img src="http://placehold.it/5" style="max-width: 100px;" alt="">
        </div>
         <button type="button" class="btn btn-default btn-danger hidden">Annuler</button>
        </div>
        </div>
        </div>
      </div>
      <div class="col-md-6">
        <label for="{{ form.title.vars.id }}" class="col-sm-2 control-label">Titre * :</label>
        <div class="col-sm-10">
        {{ form_errors(form.title) }}
        {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
          </div><br/><br/>
          <label for="{{ form.date.vars.id }}" class="col-sm-2 control-label">Date :</label>
          <div class="col-sm-4">
          {{ form_errors(form.date) }}
          {{ form_widget(form.date) }}
            </div>
      </div>
  </div>
</div>
</div><br/>
<div class="box box-primary" style="border-top-color:#820000;">
            <div class="box-body">
  <div class="row" style="padding: 10px;">
  <br/><br/>
  <label for="{{ form.description.vars.id }}" class="col-sm-2 control-label">Description :</label>
  <div class="col-sm-8">
  {{ form_errors(form.description) }}
  {{ form_widget(form.description) }}
    </div>
</div><div class="row" style="padding: 10px;">
    <br/><br/>
    <label for="{{ form.conditions.vars.id }}" class="col-sm-2 control-label">Conditions de vente :</label>
    <div class="col-sm-8">
    {{ form_errors(form.conditions) }}
    {{ form_widget(form.conditions) }}
      </div>
  </div>
  <div class="row" style="padding: 10px;">
  <br/><br/>
  <label for="nothing" class="col-sm-2 control-label">Bouton catalogue :</label>
  <div class="col-sm-8">

  {{ form_label(form.catpublished)  }}
  {{ form_errors(form.catpublished) }}
  {{ form_widget(form.catpublished) }}

    </div>
  </div>

  <div class="row" style="padding: 10px;">
  <br/><br/>
    <label for="{{ form.liveurl.vars.id }}" class="col-sm-2 control-label">URL Live :</label>
  <div class="col-sm-8">
  {{ form_errors(form.liveurl) }}
  {{ form_widget(form.liveurl) }}

    </div>
  </div>
  <div class="row" style="padding: 20px;">
         {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}
         </div>
               </div>

{{ form_rest(form) }}

 {{ form_end(form) }}
 </div>

{% endblock %}

src/HDV/AdminBundle/Resources/views/Ventes/edit.html.twig
{% extends "HDVAdminBundle:Default:index.html.twig" %}
{% block scripts %}
<script type="text/javascript">
    $(function () {

        // A change sélection de fichier
        $('#formup').find('input[type=file]').on('change', function (e) {
            var files = $(this)[0].files;

            if (files.length > 0) {
                // On part du principe qu'il n'y qu'un seul fichier
                // étant donné que l'on a pas renseigné l'attribut "multiple"
                var file = files[0],
                    $image_preview = $('#image_preview');

                // Ici on injecte les informations recoltées sur le fichier pour l'utilisateur
                $image_preview.find('.thumbnail').removeClass('hidden');
                $image_preview.find('.btn').removeClass('hidden');
                $image_preview.find('img').attr('src', window.URL.createObjectURL(file));
            }
        });

        // Bouton "Annuler"
        $('#image_preview').find('button[type="button"]').on('click', function (e) {
            e.preventDefault();

            $('#formup').find('input[name="hdv_ventesbundle_ventes[image][file]"]').val('');
            $('#image_preview').find('.thumbnail').addClass('hidden');
            $('#image_preview').find('.btn').addClass('hidden');
        });
    });

    $(".datetimepicker").datetimepicker({
    locale: 'fr',
    useCurrent: false,
    sideBySide: true
});

//$(document).ready(function(){
//  $('#hdv_ventesbundle_ventes_catpublished').iCheck({
//    checkboxClass: 'icheckbox_flat-blue',
//    radioClass: 'iradio_flat-blue'
//  });
//});
</script>
{% endblock %}
{% block body %}

<h2>Editer une vente</h2>
<div class="grad"></div>
<a href="{{ path('hdv_admin_ventes_home',{ 'period' : 'futur' }) }}" class="btn btn-default"><span class="fa fa-lg  fa-arrow-left" style="margin-right:5px;"></span> Retour</a>
<br/><br/>
<div class="box box-primary">
           <div class="box-header with-border">
             <h3 class="box-title">Principal</h3>
           </div>
            <div class="box-body">
{{ form_start(form, {'attr': {'id': 'formup'}}) }}


<br/>
  <div class="row">
      <div class="col-md-6">
        <div class="row">
            <div class="col-md-8">
        <label for="couv" class="col-sm-2 control-label" style="width: 250px">Couverture :</label>
        <a class="btn btn-info btn-lg" style="width: 100px;margin-left:18px;">
      <label for="{{ form.image.file.vars.id }}" style="width:100px;height:35px;float:left;"><i class="glyphicon glyphicon-save-file fa-3x"></i></label></a>
      {% if vente.image is not null %}
            <img src="{{ asset(vente.image.webPath) }}" style="max-height: 130px;margin-left:40px" onError="ImageLoadFailed()"/>
            {% endif %}
      {{ form_errors(form.image.file) }}
        {{ form_widget(form.image.file, {'attr': {'class': 'inputfile'}}) }}
      </div>
      <div class="col-md-4">
        <div id="image_preview" style="height:185px;">
        <div class="thumbnail hidden">
            <img src="http://placehold.it/5" style="max-width: 100px;" alt="">
        </div>
         <button type="button" class="btn btn-default btn-danger hidden">Annuler</button>
        </div>
        </div>
        </div>
      </div>
      <div class="col-md-6">
        <label for="{{ form.title.vars.id }}" class="col-sm-2 control-label">Titre * :</label>
        <div class="col-sm-10">
        {{ form_errors(form.title) }}
        {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
          </div><br/><br/>
          <label for="{{ form.date.vars.id }}" class="col-sm-2 control-label">Date :</label>
          <div class="col-sm-4">
          {{ form_errors(form.date) }}
          {{ form_widget(form.date) }}
            </div>
      </div>
  </div>
</div>
</div><br/>
<div class="box box-primary" style="border-top-color:#820000;">
            <div class="box-body">
  <div class="row" style="padding: 10px;">
  <br/><br/>
  <label for="{{ form.description.vars.id }}" class="col-sm-2 control-label">Description :</label>
  <div class="col-sm-8">
  {{ form_errors(form.description) }}
  {{ form_widget(form.description) }}
    </div>
</div><div class="row" style="padding: 10px;">
    <br/><br/>
    <label for="{{ form.conditions.vars.id }}" class="col-sm-2 control-label">Conditions de vente :</label>
    <div class="col-sm-8">
    {{ form_errors(form.conditions) }}
    {{ form_widget(form.conditions) }}
      </div>
  </div>
  <div class="row" style="padding: 10px;">
  <br/><br/>
  <label for="nothing" class="col-sm-2 control-label">Bouton catalogue :</label>
  <div class="col-sm-8">

  {{ form_label(form.catpublished)  }}
  {{ form_errors(form.catpublished) }}
  {{ form_widget(form.catpublished) }}

    </div>
  </div>
  <div class="row" style="padding: 10px;">
  <br/><br/>
    <label for="{{ form.liveurl.vars.id }}" class="col-sm-2 control-label">URL Live :</label>
  <div class="col-sm-8">
  {{ form_errors(form.liveurl) }}
  {{ form_widget(form.liveurl) }}

    </div>
  </div>
  <div class="row" style="padding: 20px;">
         {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}
         </div>
               </div>

{{ form_rest(form) }}

 {{ form_end(form) }}
 </div>

{% endblock %}

src/HDV/AdminBundle/Resources/views/Ventes/index.html.twig
{% extends "HDVAdminBundle:Default:index.html.twig" %}
{% block body %}

<h2>Ventes futures</h2>
<div class="grad"></div>
<a href="{{ path('hdv_admin_add_vente') }}" class="btn btn-default"><span class="fa fa-lg  fa-plus" style="margin-right:5px;"></span> Ajouter une vente</a>

<br/><br/>
<div class="box box-content" style="border-top-color:#511a1a;">
  <div class="box-header with-border">
          <h3 class="box-title">Liste des ventes</h3>
        </div>
  <div class="box-body content">
{{ datatable({
     'id' : 'd17',
      'js' : {
          'ajax' : path('hdv_admin_ventes_grid',{ 'period' : period }),
    'columnDefs': [
              { "width": "15%", "targets": 1 },
              { "width": "50%", "targets": 2 }
          ]
      }
  })
}}
</div>
</div>

{% endblock %}